version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
