version: "3.9"

services:
  app:
    build:
      context: .
    volumes:
      - .:/home/app/code
      - ~/.cache/huggingface:/home/app/.cache/huggingface
      - /home/m.utrobin/tmp/impruver:/home/app/tmp
      - /home/m.utrobin/models:/home/app/models
      #- .:/app
      - ~/.cache/huggingface:/root/.cache/huggingface
    network_mode: bridge
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
